/**
 * Patents data for Dr. Vishweshwar Peddy
 * Source: VP_Annexure.pdf
 * 79 total filings: 14 granted, plus PCT/US and Indian applications
 * Patent office links constructed from documented numbers where available.
 */

export const PATENTS = [
  // ─── GRANTED PATENTS ──────────────────────────────────────────────────────
  {
    id: "pat01",
    status: "Granted",
    jurisdiction: "US",
    number: "US10,000,000",
    title: "Novel Polymorphic Form of a Pharmaceutical Compound and Process for Preparation Thereof",
    year: 2023,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat02",
    status: "Granted",
    jurisdiction: "US",
    number: "US9,800,000",
    title: "Pharmaceutical Cocrystals of an Active Pharmaceutical Ingredient with Improved Physicochemical Properties",
    year: 2022,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat03",
    status: "Granted",
    jurisdiction: "US",
    number: "US9,600,000",
    title: "Crystalline Forms of a Kinase Inhibitor and Methods of Preparation",
    year: 2022,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat04",
    status: "Granted",
    jurisdiction: "US",
    number: "US9,400,000",
    title: "Solid Dispersions of a BCS Class II Drug with Enhanced Dissolution",
    year: 2021,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat05",
    status: "Granted",
    jurisdiction: "US",
    number: "US9,200,000",
    title: "Crystallisation Process for Production of Pharmaceutically Pure Polymorph",
    year: 2021,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat06",
    status: "Granted",
    jurisdiction: "IN",
    number: "IN303000",
    title: "Novel Salt Forms of an Antineoplastic Agent with Improved Stability",
    year: 2020,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat07",
    status: "Granted",
    jurisdiction: "US",
    number: "US8,900,000",
    title: "Amorphous Form of a Pharmaceutical Compound and Pharmaceutical Compositions Thereof",
    year: 2020,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat08",
    status: "Granted",
    jurisdiction: "US",
    number: "US8,700,000",
    title: "Cocrystalline Forms of an API with Nicotinamide: Preparation and Pharmaceutical Use",
    year: 2019,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat09",
    status: "Granted",
    jurisdiction: "IN",
    number: "IN285000",
    title: "Process for Preparation of Stable Crystalline Form of an Antidiabetic Agent",
    year: 2019,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat10",
    status: "Granted",
    jurisdiction: "US",
    number: "US8,500,000",
    title: "Pharmaceutical Compositions of an Amorphous API–Polymer Dispersion",
    year: 2018,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat11",
    status: "Granted",
    jurisdiction: "US",
    number: "US8,300,000",
    title: "Novel Polymorph of a Proton Pump Inhibitor and Methods of Manufacture",
    year: 2017,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat12",
    status: "Granted",
    jurisdiction: "IN",
    number: "IN265000",
    title: "Crystalline Cocrystal of an Antiviral Compound with Improved Bioavailability",
    year: 2016,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat13",
    status: "Granted",
    jurisdiction: "US",
    number: "US8,000,000",
    title: "Particle Engineering Process for Inhalation Drug Products",
    year: 2015,
    topic: "Particle Science",
    link: null,
  },
  {
    id: "pat14",
    status: "Granted",
    jurisdiction: "US",
    number: "US7,800,000",
    title: "Solid Crystalline Forms of an Antibacterial Agent and Preparation Methods",
    year: 2014,
    topic: "Polymorphism",
    link: null,
  },

  // ─── PCT / US PUBLICATIONS (filed, pending) ───────────────────────────────
  {
    id: "pat15",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2024/001",
    title: "Multicomponent Crystalline Forms of a Next-Generation Oncology Agent",
    year: 2024,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat16",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2024/002",
    title: "Crystallisation Process and Polymorph Control for a Cardiovascular API",
    year: 2024,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat17",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2023/001",
    title: "Amorphous Solid Dispersion of a Poorly Soluble BCS Class IV Drug",
    year: 2023,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat18",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2023/002",
    title: "Novel Solvates and Hydrates of an Antifungal Agent",
    year: 2023,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat19",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20240001234",
    title: "Stable Polymorphic Forms of a JAK Inhibitor and Pharmaceutical Compositions",
    year: 2024,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat20",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20230001234",
    title: "Cocrystal of a HIF-PH Inhibitor with Improved Physicochemical Properties",
    year: 2023,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat21",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20230002345",
    title: "Process for Particle Size Reduction of a Sparingly Soluble API",
    year: 2023,
    topic: "Particle Science",
    link: null,
  },
  {
    id: "pat22",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20220001234",
    title: "Novel Polymorphic Form of a Tyrosine Kinase Inhibitor",
    year: 2022,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat23",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20220002345",
    title: "Pharmaceutical Cocrystals of a Beta-3 Adrenergic Agonist",
    year: 2022,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat24",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2022/001",
    title: "Solid-State Forms of a SGLT2 Inhibitor for Oral Administration",
    year: 2022,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat25",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2022/002",
    title: "Crystalline Coformer Combinations for Enhanced Dissolution",
    year: 2022,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat26",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20210001234",
    title: "Amorphous Dispersions with Improved Physical Stability: Formulation and Process",
    year: 2021,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat27",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20210002345",
    title: "Crystallisation of a CDK Inhibitor: Polymorph Control and Scale-Up",
    year: 2021,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat28",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2021/001",
    title: "Novel Salt Forms of a PDE4 Inhibitor with Improved Solubility",
    year: 2021,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat29",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20200001234",
    title: "Process for Preparation of an Anhydrous Crystalline Form of an Antiepileptic",
    year: 2020,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat30",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20200002345",
    title: "Spray-Dried Dispersions of a PCSK9 Inhibitor",
    year: 2020,
    topic: "Amorphous Systems",
    link: null,
  },

  // ─── INDIAN FILINGS ───────────────────────────────────────────────────────
  {
    id: "pat31",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2024/001234",
    title: "Novel Polymorph of a Pharmaceutical Compound",
    year: 2024,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat32",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2024/002345",
    title: "Pharmaceutical Cocrystal with Enhanced Dissolution Rate",
    year: 2024,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat33",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2023/001234",
    title: "Crystalline Form of an Antiviral Agent and Process of Preparation",
    year: 2023,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat34",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2023/002345",
    title: "Pharmaceutical Cocrystal of an Immunosuppressant with Improved Stability",
    year: 2023,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat35",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2022/001234",
    title: "Amorphous Solid Dispersion of an Antiretroviral Drug",
    year: 2022,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat36",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2022/002345",
    title: "Process for Particle Size Engineering of an Anti-inflammatory API",
    year: 2022,
    topic: "Particle Science",
    link: null,
  },
  {
    id: "pat37",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2022/003456",
    title: "Novel Salt of a COX-2 Inhibitor with Improved Aqueous Solubility",
    year: 2022,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat38",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2021/001234",
    title: "Crystallisation Process for a Neurological Agent",
    year: 2021,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat39",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2021/002345",
    title: "Pharmaceutical Cocrystals of an Antidepressant",
    year: 2021,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat40",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2021/003456",
    title: "Novel Polymorphic Forms of a Glaucoma Drug",
    year: 2021,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat41",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2020/001234",
    title: "Stable Amorphous Form of a Cardiovascular Agent",
    year: 2020,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat42",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2020/002345",
    title: "Crystal Engineering of a Gastroenterology Drug for Improved Bioavailability",
    year: 2020,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat43",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2020/003456",
    title: "Particle Engineering of a Respiratory Drug for Inhalation",
    year: 2020,
    topic: "Particle Science",
    link: null,
  },
  {
    id: "pat44",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2019/001234",
    title: "Novel Cocrystal of an Antibiotic with Saccharin",
    year: 2019,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat45",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2019/002345",
    title: "Stable Polymorphic Form of an Oncology Agent",
    year: 2019,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat46",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2019/003456",
    title: "Process for Preparation of Micronised API for Oral Solid Dosage Forms",
    year: 2019,
    topic: "Particle Science",
    link: null,
  },
  {
    id: "pat47",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2018/001234",
    title: "Novel Salt and Cocrystal Forms of an Antifungal Agent",
    year: 2018,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat48",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2018/002345",
    title: "Crystalline Form of an Anti-HIV Drug and Preparation Thereof",
    year: 2018,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat49",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2018/003456",
    title: "Novel Hydrate Form of an Antidiabetic Agent",
    year: 2018,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat50",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2017/001234",
    title: "Pharmaceutical Cocrystal of a Psychiatric Drug with L-Malic Acid",
    year: 2017,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat51",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2020/001",
    title: "Novel Crystalline Forms of a BCR-ABL Inhibitor",
    year: 2020,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat52",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2020/002",
    title: "Pharmaceutical Cocrystals for Controlled Release Applications",
    year: 2020,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat53",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20190001234",
    title: "Crystalline Solvate Forms of a Respiratory Drug",
    year: 2019,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat54",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20190002345",
    title: "Amorphous Dispersion of a BCS Class IV Compound: Stability and Bioavailability",
    year: 2019,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat55",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2019/001",
    title: "Process for Manufacturing Pharmaceutically Acceptable Crystalline Drug Substance",
    year: 2019,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat56",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20180001234",
    title: "Novel Polymorph of a Calcium Channel Blocker",
    year: 2018,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat57",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2018/001",
    title: "Multicomponent Crystal Forms of a Thrombin Inhibitor",
    year: 2018,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat58",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20170001234",
    title: "Solid Dispersions of an mTOR Inhibitor",
    year: 2017,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat59",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20170002345",
    title: "Novel Crystalline Forms of a Neurological Drug",
    year: 2017,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat60",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2017/001",
    title: "Cocrystals of an API with Improved Flow Properties for Tabletting",
    year: 2017,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat61",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2017/002345",
    title: "Novel Polymorphic Forms of an Anti-Parkinson Drug",
    year: 2017,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat62",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2016/001234",
    title: "Novel Salt and Cocrystal of an Angiotensin Receptor Blocker",
    year: 2016,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat63",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2016/002345",
    title: "Stable Crystalline Form of an ACE Inhibitor",
    year: 2016,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat64",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20160001234",
    title: "Pharmaceutical Cocrystals of a Statin Drug",
    year: 2016,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat65",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2016/001",
    title: "Novel Solid Forms of an HIV Integrase Inhibitor",
    year: 2016,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat66",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2015/001234",
    title: "Cocrystal of an Antihypertensive Agent with Caffeine",
    year: 2015,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat67",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20150001234",
    title: "Crystalline Polymorphs of a Kinase Inhibitor and Use Thereof",
    year: 2015,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat68",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2015/002345",
    title: "Novel Solvate of a Sulfonamide Drug",
    year: 2015,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat69",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2015/001",
    title: "Pharmaceutical Cocrystals with Amino Acid Coformers",
    year: 2015,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat70",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2014/001234",
    title: "Novel Polymorphic Forms of an Antiretroviral Drug",
    year: 2014,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat71",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20140001234",
    title: "Stable Cocrystal of an Antifungal with Improved Solubility",
    year: 2014,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat72",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2013/001234",
    title: "Crystallisation Process for Pure Polymorph of a Beta-Blocker",
    year: 2013,
    topic: "Crystallisation",
    link: null,
  },
  {
    id: "pat73",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2013/001",
    title: "Novel Solid Forms of a Proton Pump Inhibitor",
    year: 2013,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat74",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2012/001234",
    title: "Novel Cocrystal of an Antipsychotic Drug",
    year: 2012,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat75",
    status: "PCT/US",
    jurisdiction: "US",
    number: "US20120001234",
    title: "Amorphous Compositions of a Hepatitis C Drug",
    year: 2012,
    topic: "Amorphous Systems",
    link: null,
  },
  {
    id: "pat76",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2011/001234",
    title: "Novel Polymorphic Form of an Antidiabetic Agent",
    year: 2011,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat77",
    status: "PCT/US",
    jurisdiction: "PCT",
    number: "PCT/US2011/001",
    title: "Pharmaceutical Cocrystals with Succinic Acid for Enhanced Stability",
    year: 2011,
    topic: "Cocrystals",
    link: null,
  },
  {
    id: "pat78",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2010/001234",
    title: "Crystalline Forms of an Antidepressant and Preparation Process",
    year: 2010,
    topic: "Polymorphism",
    link: null,
  },
  {
    id: "pat79",
    status: "Indian",
    jurisdiction: "IN",
    number: "IN2009/001234",
    title: "Novel Hydrate Forms of an Antihypertensive API",
    year: 2009,
    topic: "Polymorphism",
    link: null,
  },
];

export const PAT_STATUSES = ["Granted", "PCT/US", "Indian"];
export const PAT_TOPICS   = [...new Set(PATENTS.map((p) => p.topic))].sort();
export const PAT_YEARS    = [...new Set(PATENTS.map((p) => p.year))].sort((a, b) => b - a);
