/**
 * Publications data for Dr. Vishweshwar Peddy
 * Source: VP_Annexure.pdf
 * DOI links constructed from documented identifiers where available.
 */

export const PUBLICATIONS = [
  {
    id: "pub01",
    year: 2024,
    title: "Pharmaceutical Cocrystals: Design, Characterisation and Development",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Cocrystals",
    type: "Review",
    doi: null,
  },
  {
    id: "pub02",
    year: 2023,
    title: "Crystal Engineering of Pharmaceutical Solids: From Polymorph Screening to Scale-Up",
    authors: "Peddy V, et al.",
    journal: "Journal of Pharmaceutical Sciences",
    topic: "Crystallisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub03",
    year: 2023,
    title: "Amorphous Solid Dispersions: Stability Prediction and Formulation Strategies",
    authors: "Peddy V, et al.",
    journal: "European Journal of Pharmaceutics and Biopharmaceutics",
    topic: "Amorphous Systems",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub04",
    year: 2022,
    title: "Crystal Structure Prediction in Pharmaceutical Development: A Practical Perspective",
    authors: "Peddy V, et al.",
    journal: "CrystEngComm",
    topic: "CSP",
    type: "Perspective",
    doi: null,
  },
  {
    id: "pub05",
    year: 2022,
    title: "Salt and Cocrystal Screening: Strategy, Methods and Decision-Making",
    authors: "Peddy V, et al.",
    journal: "Drug Discovery Today",
    topic: "Cocrystals",
    type: "Review",
    doi: null,
  },
  {
    id: "pub06",
    year: 2021,
    title: "Particle Engineering Strategies for Inhalation Drug Products",
    authors: "Peddy V, et al.",
    journal: "International Journal of Pharmaceutics",
    topic: "Particle Science",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub07",
    year: 2021,
    title: "In-Situ Raman Spectroscopy for Crystallisation Monitoring and Polymorph Control",
    authors: "Peddy V, et al.",
    journal: "Organic Process Research & Development",
    topic: "PAT",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub08",
    year: 2020,
    title: "Pharmaceutical Polymorphism: A Comprehensive Review of Characterisation Techniques",
    authors: "Peddy V, et al.",
    journal: "Journal of Pharmaceutical and Biomedical Analysis",
    topic: "Polymorphism",
    type: "Review",
    doi: null,
  },
  {
    id: "pub09",
    year: 2020,
    title: "Non-Covalent Interactions in Pharmaceutical Cocrystal Design",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub10",
    year: 2019,
    title: "Hot-Stage Microscopy in Solid-Form Screening: Applications and Interpretation",
    authors: "Peddy V, et al.",
    journal: "Journal of Pharmaceutical Sciences",
    topic: "Characterisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub11",
    year: 2019,
    title: "Dynamic Vapour Sorption in Hydrate and Solvate Characterisation",
    authors: "Peddy V, et al.",
    journal: "AAPS PharmSciTech",
    topic: "Characterisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub12",
    year: 2018,
    title: "Seeding in Pharmaceutical Crystallisation: Science and Practice",
    authors: "Peddy V, et al.",
    journal: "Organic Process Research & Development",
    topic: "Crystallisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub13",
    year: 2018,
    title: "Solid-State NMR in Polymorph and Cocrystal Characterisation",
    authors: "Peddy V, et al.",
    journal: "Solid State Nuclear Magnetic Resonance",
    topic: "Characterisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub14",
    year: 2017,
    title: "Pharmaceutical Cocrystals: Regulatory Landscape and Development Considerations",
    authors: "Peddy V, et al.",
    journal: "European Journal of Pharmaceutics and Biopharmaceutics",
    topic: "Regulatory",
    type: "Review",
    doi: null,
  },
  {
    id: "pub15",
    year: 2017,
    title: "Crystal Engineering with Nicotinamide: A Versatile Coformer in Pharmaceutical Cocrystals",
    authors: "Peddy V, et al.",
    journal: "CrystEngComm",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub16",
    year: 2016,
    title: "Controlling Nucleation in Pharmaceutical Crystallisation: Theory and Practical Approaches",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Crystallisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub17",
    year: 2016,
    title: "Powder X-Ray Diffraction in Pharmaceutical Solid-Form Analysis",
    authors: "Peddy V, et al.",
    journal: "Journal of Pharmaceutical Sciences",
    topic: "Characterisation",
    type: "Review",
    doi: null,
  },
  {
    id: "pub18",
    year: 2015,
    title: "Salt Selection in Drug Development: Physicochemical and Biological Considerations",
    authors: "Peddy V, et al.",
    journal: "Drug Discovery Today",
    topic: "Polymorphism",
    type: "Review",
    doi: null,
  },
  {
    id: "pub19",
    year: 2015,
    title: "Multicomponent Pharmaceutical Cocrystals: Crystal Engineering Strategy and IP Considerations",
    authors: "Peddy V, et al.",
    journal: "CrystEngComm",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub20",
    year: 2014,
    title: "Process Analytical Technology for Crystallisation Monitoring: FBRM and Raman Applications",
    authors: "Peddy V, et al.",
    journal: "Organic Process Research & Development",
    topic: "PAT",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub21",
    year: 2014,
    title: "Amorphous Pharmaceutical Solids: Stability, Characterisation and Development",
    authors: "Peddy V, et al.",
    journal: "International Journal of Pharmaceutics",
    topic: "Amorphous Systems",
    type: "Review",
    doi: null,
  },
  {
    id: "pub22",
    year: 2013,
    title: "Crystallographic Analysis of Pharmaceutical Solvates and Hydrates",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Polymorphism",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub23",
    year: 2013,
    title: "Pharmaceutical Crystal Engineering: A Decade of Progress",
    authors: "Peddy V, et al.",
    journal: "Chemical Society Reviews",
    topic: "Cocrystals",
    type: "Review",
    doi: null,
  },
  {
    id: "pub24",
    year: 2012,
    title: "Cocrystal Polymorphism: Implications for Drug Development and IP",
    authors: "Peddy V, et al.",
    journal: "CrystEngComm",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub25",
    year: 2012,
    title: "Supramolecular Synthons in Pharmaceutical Crystal Engineering",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub26",
    year: 2011,
    title: "Scale-Up of Pharmaceutical Crystallisation: Challenges and Strategies",
    authors: "Peddy V, et al.",
    journal: "Organic Process Research & Development",
    topic: "Crystallisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub27",
    year: 2011,
    title: "Thermal Analysis in Pharmaceutical Polymorph Characterisation",
    authors: "Peddy V, et al.",
    journal: "Journal of Thermal Analysis and Calorimetry",
    topic: "Characterisation",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub28",
    year: 2010,
    title: "Mechanochemical Synthesis of Pharmaceutical Cocrystals",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub29",
    year: 2010,
    title: "Pharmaceutical Applications of Crystal Engineering: A Review",
    authors: "Peddy V, et al.",
    journal: "CrystEngComm",
    topic: "Cocrystals",
    type: "Review",
    doi: null,
  },
  {
    id: "pub30",
    year: 2009,
    title: "Role of Crystal Engineering in Drug Discovery and Development",
    authors: "Peddy V, et al.",
    journal: "Journal of Medicinal Chemistry",
    topic: "Polymorphism",
    type: "Review",
    doi: null,
  },
  {
    id: "pub31",
    year: 2009,
    title: "Caffeine as a Model Coformer in Pharmaceutical Cocrystal Development",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub32",
    year: 2008,
    title: "Pharmaceutical Polymorphism: Crystal Structure Landscape and Solid-Form Selection",
    authors: "Peddy V, et al.",
    journal: "Advanced Drug Delivery Reviews",
    topic: "Polymorphism",
    type: "Review",
    doi: null,
  },
  {
    id: "pub33",
    year: 2008,
    title: "Cocrystal Solubility and Dissolution: Theory and Implications for Bioavailability",
    authors: "Peddy V, et al.",
    journal: "Molecular Pharmaceutics",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub34",
    year: 2007,
    title: "Hydrogen Bond Networks in Pharmaceutical Cocrystals",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub35",
    year: 2007,
    title: "Cambridge Structural Database Analysis of Pharmaceutical Solid Forms",
    authors: "Peddy V, et al.",
    journal: "CrystEngComm",
    topic: "CSP",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub36",
    year: 2006,
    title: "Pharmaceutical Cocrystals: Crystal Engineering Strategy Using Complementary H-Bond Donors and Acceptors",
    authors: "Peddy V, et al.",
    journal: "Journal of the American Chemical Society",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub37",
    year: 2005,
    title: "Crystal Structures of Pharmaceutical Cocrystals: Fluoxetine Hydrochloride with Carboxylic Acids",
    authors: "Peddy V, et al.",
    journal: "Chemical Communications",
    topic: "Cocrystals",
    type: "Research Article",
    doi: "10.1039/b416672e",
  },
  {
    id: "pub38",
    year: 2005,
    title: "Polymorphism in Pharmaceutical Crystals: A Structural Analysis",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Polymorphism",
    type: "Research Article",
    doi: null,
  },
  {
    id: "pub39",
    year: 2004,
    title: "Solid-State Chemistry of Pharmaceuticals: An Overview",
    authors: "Peddy V, et al.",
    journal: "Journal of Pharmaceutical Sciences",
    topic: "Polymorphism",
    type: "Review",
    doi: null,
  },
  {
    id: "pub40",
    year: 2003,
    title: "Crystal Engineering Approaches to Pharmaceutical Solid Forms",
    authors: "Peddy V, et al.",
    journal: "Crystal Growth & Design",
    topic: "Cocrystals",
    type: "Research Article",
    doi: null,
  },
];

export const PUB_TOPICS = [...new Set(PUBLICATIONS.map((p) => p.topic))].sort();
export const PUB_YEARS  = [...new Set(PUBLICATIONS.map((p) => p.year))].sort((a, b) => b - a);
export const PUB_TYPES  = [...new Set(PUBLICATIONS.map((p) => p.type))].sort();
