export const CAREER = [
  { id: 'uoh', period: '1999–2004', chapter: 'Structural foundations', org: 'University of Hyderabad', role: 'PhD', focus: 'Understanding the relationships that organize the solid state.', detail: 'Doctoral research brought together small-molecule synthesis, polymorphism, crystal engineering, modelling and X-ray crystallography. The work included single-crystal growth, structure solution and refinement, and computational studies of polymorph stability.', evidence: 'Crystal engineering · Crystallography · Modelling', pages: '7', doc: 'cv', link: '/publications?year=2003', linkLabel: 'Explore the early research' },
  { id: 'usf', period: '2004–2006', chapter: 'Pharmaceutical crystal engineering', org: 'University of South Florida', role: 'Postdoctoral research', focus: 'Connecting molecular organization with pharmaceutical solid forms.', detail: 'Industry-sponsored projects with Transform Pharmaceuticals, a Johnson & Johnson company, focused on pharmaceutical cocrystal design, synthesis, characterization and crystallization. Alongside the research, he mentored graduate students contributing to PhD programs.', evidence: 'Pharmaceutical cocrystals · Graduate mentoring', pages: '3', doc: 'annexure', link: '/publications#publication-2', linkLabel: 'Read the 2006 review' },
  { id: 'drl', period: '2006–2018', chapter: 'Solid forms in development', org: 'Dr. Reddy’s Laboratories', role: 'Principal Scientist', focus: 'Establishing solid-form strategies across generic APIs and drug discovery.', detail: 'Led polymorph screening and analytical teams, developed novel forms and crystallization processes, and worked with portfolio, IP and regulatory teams. Responsibilities included high-throughput screening infrastructure, stability evaluation and development contributions associated with eight US-DMF filings.', evidence: 'Solid-form selection · Analytical leadership · IP support', pages: '3–4', doc: 'cv', link: '/innovation#roxadustat', linkLabel: 'Explore documented development work' },
  { id: 'glenmark', period: '2018–2023', chapter: 'From process to plant', org: 'Glenmark Life Sciences', role: 'Senior Principal Scientist — Process Chemistry, Crystallization & Polymorphism', focus: 'Bringing materials science, process chemistry and manufacturing together.', detail: 'Led crystallization, materials science and process chemistry work supporting route selection, API development, technology transfer and plant validation. Mentored process chemistry teams and supported cost-improvement initiatives and commercial supply. Glenmark Life Sciences is now known as Alivus Life Sciences.', evidence: 'Route selection · Technology transfer · Plant validation', pages: '3', doc: 'cv', link: '/innovation#tafamidis', linkLabel: 'Browse the development record' },
  { id: 'sai', period: '2023–Present', chapter: 'Particle-science leadership', org: 'Sai Life Sciences', role: 'Senior Director & Head — Particle Science & Engineering', focus: 'Building the people, methods and capabilities that support development.', detail: 'Leads materials science, solid-form selection, crystallization, PAT integration and particle engineering across global innovator programs. The supplied CV documents 40+ early- and late-phase client programs, technical client reviews, scale-up support, CAPEX planning and internal scientific training through Sai Academy.', evidence: '40+ client programs · PAT integration · Capability building', pages: '2', doc: 'cv', link: '/research#particle-science', linkLabel: 'Explore particle science' },
];
export const RECOGNITION = [
  ['2014', 'Best Complex Product Development and Delivery — Team Award', 'UTSAV, Dr. Reddy’s Laboratories'],
  ['2013', 'Best Innovation — Team Award', 'UTSAV, Dr. Reddy’s Laboratories'],
  ['2012', 'Best Innovation — Team Award', 'UTSAV, Dr. Reddy’s Laboratories'],
  ['2011', 'Best Idea Generation — Team Award', 'UTSAV, Dr. Reddy’s Laboratories'],
  ['2009–2010', 'Chairman’s Excellence Award — Best Innovation Team', 'Dr. Reddy’s Laboratories'],
  ['2008', 'Cost-Effective Initiatives Award', 'Discovery Research, Dr. Reddy’s Laboratories'],
];