import { useState } from 'react';

const Motif = ({ x = 0, y = 0, angle = 0, color = '#a9c4a9', scale = 1 }) => <g transform={`translate(${x} ${y}) rotate(${angle}) scale(${scale})`}><path d="M-10 -15 8 -18 17 0 8 18 -10 15 -17 0Z" fill="none" stroke={color} strokeWidth="1.2" /><path d="M-10 -15 0 0 8 -18M0 0 17 0M0 0 8 18M0 0 -10 15M0 0 -17 0" fill="none" stroke={color} strokeWidth=".6" opacity=".65" /></g>;

export const ScienceFigure = ({ id = 'solid-form-figure' }) => <figure data-testid={id}><div className="science-plate"><div className="plate-heading"><span>Reading the solid state</span><span>Conceptual study / 01</span></div><svg viewBox="0 0 660 240" role="img" aria-label="Three conceptual scales: repeated constituent motifs, an ordered solid, and different external particle outlines. These are illustrations, not measured structures."><g>{Array.from({ length: 9 }, (_, i) => <Motif key={i} x={53 + (i % 3) * 47} y={62 + Math.floor(i / 3) * 52} angle={i % 2 ? 25 : -15} scale={.8} />)}</g><path d="M213 118h31m-6-5 6 5-6 5M435 118h31m-6-5 6 5-6 5" fill="none" stroke="#829784" /><g>{Array.from({ length: 12 }, (_, i) => <Motif key={i} x={291 + (i % 3) * 36 + Math.floor(i / 3) * 8} y={42 + Math.floor(i / 3) * 43} scale={.95} />)}</g><g stroke="#b5cdb5" strokeWidth="1.3" fill="none"><path d="m515 76 43-26 30 15v57l-43 26-30-15Z M515 76l30 15 43-26M545 91v57"/><path d="m524 188 66-22 26 10v18l-66 23-26-11Z M524 188l26 10 66-22M550 198v19"/></g><path d="M47 216h100M290 216h100M514 235h99" stroke="#637a68" strokeWidth=".6" /></svg><div className="plate-labels"><div><strong>Arrangement</strong><p>How constituents relate</p></div><div><strong>Solid form</strong><p>How a solid is organized</p></div><div><strong>Particle attributes</strong><p>Size and external shape</p></div></div></div><figcaption className="figure-caption" data-testid={`${id}-caption`}>Conceptual illustration. No measured structure, scale or experimental result is represented.</figcaption></figure>;

export const ProgramArt = () => <svg className="program-mini-art" viewBox="0 0 430 145" aria-hidden="true">{Array.from({ length: 12 }, (_, i) => <g key={i}><Motif x={50 + (i % 6) * 63} y={45 + Math.floor(i / 6) * 59} color="#4d7055" scale={.8} /><path d={`M${72+(i%6)*63} ${42+Math.floor(i/6)*59}l6-6 6 6-6 6Z`} stroke="#955e45" strokeWidth="1" fill="none" /></g>)}</svg>;

const OPTIONS = [
  { id: 'polymorphs', label: 'Polymorphs', title: 'Same composition. Different arrangements.', text: 'Polymorphs have the same chemical composition but different crystal structures. Form selection weighs the relevant material properties, stability and development context—not a universal “best” form.' },
  { id: 'salts', label: 'Salts', title: 'An ionic solid-form option.', text: 'Salt formation involves ionization and an appropriate counterion. It is not simply a different packing of the unchanged neutral components. Screening and characterization establish the relevant form.' },
  { id: 'cocrystals', label: 'Cocrystals', title: 'Distinct constituents in one crystal.', text: 'Cocrystal design brings an active ingredient and a coformer into a crystalline phase. The source documents CSD-informed crystal engineering and advanced characterization of pharmaceutical cocrystals.' },
  { id: 'amorphous', label: 'Amorphous / ASD', title: 'Beyond crystalline order.', text: 'An amorphous form lacks long-range crystalline order. An amorphous solid dispersion incorporates a drug into a carrier system. Each requires its own characterization and stability assessment.' },
];
export const FormComparison = () => {
  const [selected, setSelected] = useState('polymorphs');
  const item = OPTIONS.find(o => o.id === selected);
  return <figure className="form-comparison" data-testid="form-comparison"><div className="form-controls" aria-label="Compare solid-form options">{OPTIONS.map(o => <button key={o.id} type="button" aria-pressed={selected === o.id} aria-controls="comparison-description" onClick={() => setSelected(o.id)} data-testid={`form-option-${o.id}`}>{o.label}</button>)}</div><div className="comparison-body"><svg viewBox="0 0 230 190" role="img" aria-label={`Conceptual ${item.label} illustration using abstract constituent shapes, not atoms or measured coordinates.`}>{selected === 'amorphous' && <path d="M12 12h206v166H12Z" fill="#d4ddce" stroke="#a8b6a1" strokeDasharray="4 4" />}{Array.from({ length: 9 }, (_, i) => <g key={i}><Motif x={44 + (i % 3) * 64 + (selected === 'amorphous' ? (i % 2 ? 9 : -8) : 0)} y={39 + Math.floor(i / 3) * 53} angle={selected === 'amorphous' ? i * 37 : selected === 'polymorphs' ? 22 : 0} color="#496c50" scale={.9} />{selected === 'cocrystals' && <path d={`M${65+(i%3)*64} ${38+Math.floor(i/3)*53}l6-6 6 6-6 6Z`} fill="none" stroke="#8c4934" />}{selected === 'salts' && <text x={62+(i%3)*64} y={43+Math.floor(i/3)*53} fontSize="14" fill="#8c4934">{i%2 ? '−' : '+'}</text>}</g>)}</svg><div id="comparison-description" aria-live="polite" data-testid="comparison-description"><h3>{item.title}</h3><p>{item.text}</p></div></div><figcaption className="comparison-caption">Conceptual illustrations; motifs are not atom identities. No compound-specific structures or measured data.</figcaption></figure>;
};